#lang racket
(define graph1
  '((entity e0)
    (entity e1)
    (entity e2)
    (entity e3)
    (entity e4)
    (entity e5)
    (wasDerivedFrom d0 e1 e0)
    (wasDerivedFrom d1 e2 e1)
    (wasDerivedFrom d2 e3 e2)
    (wasDerivedFrom d3 e4 e3)
    (wasDerivedFrom d4 e4 e5)
    (wasDerivedFrom d5 e5 e0)))
 
(define graph2
  '((entity e0)
    (entity e1)
    (entity e2)
    (entity e3)
    (entity e4)
    (wasDerivedFrom d0 e1 e0)
    (wasDerivedFrom d1 e2 e1)
    (wasDerivedFrom d2 e3 e2)
    (wasDerivedFrom d3 e4 e3)
    (wasDerivedFrom d4 e3 e1)
    (wasDerivedFrom d5 e3 e0)))
 
(define graph3
  '((entity e0)
    (entity e1)
    (entity e2)
    (entity e3)
    (entity e4)
    (entity e5)
    (entity e6)
    (wasDerivedFrom d0 e0 e1)
    (wasDerivedFrom d1 e0 e2)
    (wasDerivedFrom d2 e1 e3)
    (wasDerivedFrom d3 e1 e4)
    (wasDerivedFrom d4 e2 e3)
    (wasDerivedFrom d5 e2 e4)
    (wasDerivedFrom d6 e3 e5)
    (wasDerivedFrom d7 e4 e5)
    (wasDerivedFrom d8 e0 e5)
    (wasDerivedFrom d9 e4 e3)
    (wasDerivedFrom d10 e3 e6)
    (wasDerivedFrom d11 e4 e6)
    (wasDerivedFrom d12 e6 e5)))
 
(define graph4
  '((entity e0)
    (entity e1)
    (entity e2)
    (entity e3)
    (entity e4)
    (entity e5)
    (entity e6)
    (entity e7)
    (entity e8)
    (entity e9)
    (entity e10)
    (entity e11)
    (entity e12)
    (entity e13)
    (entity e14)
    (entity e15)
    (wasDerivedFrom d0 e1 e0)
    (wasDerivedFrom d1 e2 e0)
    (wasDerivedFrom d2 e3 e0)
    (wasDerivedFrom d3 e4 e2)
    (wasDerivedFrom d4 e4 e5)
    (wasDerivedFrom d5 e4 e6)
    (wasDerivedFrom d6 e4 e0)
    (wasDerivedFrom d7 e5 e1)
    (wasDerivedFrom d8 e6 e2)
    (wasDerivedFrom d9 e6 e3)
    (wasDerivedFrom d10 e6 e0)
    (wasDerivedFrom d11 e8 e4)
    (wasDerivedFrom d12 e8 e9)
    (wasDerivedFrom d13 e8 e10)
    (wasDerivedFrom d14 e8 e11)
    (wasDerivedFrom d15 e8 e12)
    (wasDerivedFrom d16 e8 e5)
    (wasDerivedFrom d17 e8 e6)
    (wasDerivedFrom d18 e8 e0)
    (wasDerivedFrom d19 e9 e1)
    (wasDerivedFrom d20 e9 e5)
    (wasDerivedFrom d21 e9 e10)
    (wasDerivedFrom d22 e10 e5)
    (wasDerivedFrom d23 e11 e6)
    (wasDerivedFrom d24 e11 e12)
    (wasDerivedFrom d25 e11 e13)
    (wasDerivedFrom d26 e11 e15)
    (wasDerivedFrom d27 e12 e13)
    (wasDerivedFrom d28 e12 e14)
    (wasDerivedFrom d29 e13 e14)
    (wasDerivedFrom d30 e14 e15)
    (wasDerivedFrom d31 e8 e7)))

(define statement-id cadr)
(define derivation-src caddr)
(define derivation-dst cadddr)

(define helper
  (lambda (e l)
    (cond((null? l) '())
    ((equal? (derivation-src (car l)) e)
     (cons (car l) (helper e (cdr l))))
    (else (helper e (cdr l))))))

(define successors 
  (lambda (entity graph)
    (cond((null? graph) '())
      ((equal? (caar graph) 'wasDerivedFrom)
       (begin
       (helper entity (cons (car graph) (cdr graph)))))
       (else(successors entity (cdr graph))))))

(define make-derivation-tree
  (lambda (entity graph)
    (helper4 entity (successors entity graph) graph)))
 
(define helper3
  (lambda (l g)
    (if(null? l)
       '()
       (cons (cons (derivation-dst (car l)) (helper3 (successors (derivation-dst (car l)) g) g))(helper3 (cdr l) g)))))

(define helper4
  (lambda (e l g)
    (if(null? l)
       (list e)
      (cons e (helper3 l g)))))

(display (equal? (make-derivation-tree 'e0 graph1) '(e0)                                                                                                                                                                                                                                                                                                                                      ))(newline)
(display (equal? (make-derivation-tree 'e1 graph1) '(e1 (e0))                                                                                                                                                                                                                                                                                                                                 ))(newline)
(display (equal? (make-derivation-tree 'e2 graph1) '(e2 (e1 (e0)))                                                                                                                                                                                                                                                                                                                            ))(newline)
(display (equal? (make-derivation-tree 'e3 graph1) '(e3 (e2 (e1 (e0))))                                                                                                                                                                                                                                                                                                                       ))(newline)
(display (equal? (make-derivation-tree 'e4 graph1) '(e4 (e3 (e2 (e1 (e0)))) (e5 (e0)))                                                                                                                                                                                                                                                                                                        ))(newline)
(display (equal? (make-derivation-tree 'e5 graph1) '(e5 (e0))                                                                                                                                                                                                                                                                                                                                 ))(newline)
(display (equal? (make-derivation-tree 'e0 graph2) '(e0)                                                                                                                                                                                                                                                                                                                                      ))(newline)
(display (equal? (make-derivation-tree 'e1 graph2) '(e1 (e0))                                                                                                                                                                                                                                                                                                                                 ))(newline)
(display (equal? (make-derivation-tree 'e2 graph2) '(e2 (e1 (e0)))                                                                                                                                                                                                                                                                                                                            ))(newline)
(display (equal? (make-derivation-tree 'e3 graph2) '(e3 (e2 (e1 (e0))) (e1 (e0)) (e0))                                                                                                                                                                                                                                                                                                        ))(newline)
(display (equal? (make-derivation-tree 'e4 graph2) '(e4 (e3 (e2 (e1 (e0))) (e1 (e0)) (e0)))                                                                                                                                                                                                                                                                                                   ))(newline)
(display (equal? (make-derivation-tree 'e0 graph3) '(e0 (e1 (e3 (e5) (e6 (e5))) (e4 (e5) (e3 (e5) (e6 (e5))) (e6 (e5)))) (e2 (e3 (e5) (e6 (e5))) (e4 (e5) (e3 (e5) (e6 (e5))) (e6 (e5)))) (e5))                                                                                                                                                                                               ))(newline)
(display (equal? (make-derivation-tree 'e1 graph3) '(e1 (e3 (e5) (e6 (e5))) (e4 (e5) (e3 (e5) (e6 (e5))) (e6 (e5))))                                                                                                                                                                                                                                                                          ))(newline)
(display (equal? (make-derivation-tree 'e2 graph3) '(e2 (e3 (e5) (e6 (e5))) (e4 (e5) (e3 (e5) (e6 (e5))) (e6 (e5))))                                                                                                                                                                                                                                                                          ))(newline)
(display (equal? (make-derivation-tree 'e3 graph3) '(e3 (e5) (e6 (e5)))                                                                                                                                                                                                                                                                                                                       ))(newline)
(display (equal? (make-derivation-tree 'e4 graph3) '(e4 (e5) (e3 (e5) (e6 (e5))) (e6 (e5)))                                                                                                                                                                                                                                                                                                   ))(newline)
(display (equal? (make-derivation-tree 'e5 graph3) '(e5)                                                                                                                                                                                                                                                                                                                                      ))(newline)
(display (equal? (make-derivation-tree 'e6 graph3) '(e6 (e5))                                                                                                                                                                                                                                                                                                                                 ))(newline)
(display (equal? (make-derivation-tree 'e8 graph4) '(e8 (e4 (e2 (e0)) (e5 (e1 (e0))) (e6 (e2 (e0)) (e3 (e0)) (e0)) (e0)) (e9 (e1 (e0)) (e5 (e1 (e0))) (e10 (e5 (e1 (e0))))) (e10 (e5 (e1 (e0)))) (e11 (e6 (e2 (e0)) (e3 (e0)) (e0)) (e12 (e13 (e14 (e15))) (e14 (e15))) (e13 (e14 (e15))) (e15)) (e12 (e13 (e14 (e15))) (e14 (e15))) (e5 (e1 (e0))) (e6 (e2 (e0)) (e3 (e0)) (e0)) (e0) (e7))  ))(newline)